### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by HumHongeKamyaab** [daviwil/dotcrafter.el#1]
The installation process given in readme is not working,
may be following should be right way 
```
(use-package dotcrafter
  :straight '(dotcrafter :host github :repo "daviwil/dotcrafter" :branch "main")
  :custom
  (dotcrafter-dotfiles-folder "~/.dotfiles")
  (dotcrafter-org-files '("Emacs.org" "Desktop.org")))
```

**Comment by daviwil** [comment]
What error do you get?  I updated the instructions this morning to use `:repo "daviwil/dotcrafter.el"` since I renamed the repo from `dotcrafter`, maybe that's the issue?

**Comment by HumHongeKamyaab** [comment]
yes, also default branch is "main" not "master". The above works for me.

**Comment by daviwil** [comment]
Updated the recipe with commit 40bfce5.  Thanks for letting me know!
