### ISSUE TITLE
mention tangld

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [daviwil/dotcrafter.el#2]
First, this is a _really_ good idea.

I wanted to mention [tangld](https://github.com/aldrichtr/tangld), a similar project that attempts to do the same thing as this one. Both projects are in their early stages. Perhaps some collaboration can happen, or perhaps one project can merge with the other.

**Comment by daviwil** [comment]
Thanks Luis!  For now I think it might be best for both of these packages to be developed with their own ideas to see what comes out of them before figuring out how to merge them.  I'm also trying to develop this in a straight line for the Learning Emacs Lisp series I'm working on, so collaborating won't be appropriate just yet.

Thanks for letting me know about tangld though, I'll keep an eye on it!
